name: Jekyll Build on Contentful Publish Event
on:
  repository_dispatch:
    types: [publish-event]
jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
    secrets:
      ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      GLAMELAB_CONTENTFUL_SPACE_ID: ${{ secrets.GLAMELAB_CONTENTFUL_SPACE_ID }}
      GLAMELAB_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.GLAMELAB_CONTENTFUL_ACCESS_TOKEN }}
